"""
Dev-only: generate a synthetic data/raw/prices.parquet that mimics the shape
yfinance would produce, so the downstream pipeline (compute_scores → compute_rrg
→ build_site) can be smoke-tested without network access.

DO NOT use the output of this script for any actual analysis. Real refreshes go
through scripts/ingest_prices.py.

Run: python scripts/_dev_seed.py
Output: data/raw/prices.parquet  (long: date, ticker, close)
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "data" / "raw"
RAW_DIR.mkdir(parents=True, exist_ok=True)

# Same universe + benchmark as ingest_prices.py
UNIVERSE: list[tuple[str, str, float, float]] = [
    # (commodity, ticker, starting_price, annualised_vol)
    ("Lithium",      "LIT",     30.0, 0.45),
    ("Uranium",      "URA",     20.0, 0.40),
    ("Copper",       "COPX",    25.0, 0.30),
    ("Gold",         "GLD",    150.0, 0.15),
    ("Silver",       "SLV",     20.0, 0.28),
    ("Rare Earths",  "REMX",    50.0, 0.40),
    ("Crude Oil",    "USO",     50.0, 0.35),
    ("Nat Gas",      "UNG",     12.0, 0.55),
    ("PGMs",         "PPLT",    90.0, 0.25),
    ("Iron Ore",     "IRON.AX",  3.5, 0.30),
    ("Thermal Coal", "BTU",     20.0, 0.45),
    ("Nickel",       "PICK",    35.0, 0.30),
    ("Benchmark",    "^AXJO", 6500.0, 0.13),
]

WEEKS = 530          # ~10 years of Fridays
SEED = 42


def synthetic_walk(start_price: float, ann_vol: float, drift: float,
                   weeks: int, rng: np.random.Generator) -> np.ndarray:
    """Geometric Brownian motion on weekly bars."""
    dt = 1 / 52
    shocks = rng.normal(loc=(drift - 0.5 * ann_vol ** 2) * dt,
                        scale=ann_vol * np.sqrt(dt),
                        size=weeks)
    log_path = np.cumsum(shocks)
    return start_price * np.exp(log_path)


def main() -> int:
    rng = np.random.default_rng(SEED)
    end = pd.Timestamp.utcnow().tz_convert("UTC").normalize()
    # Snap to Friday
    end = end - pd.Timedelta(days=(end.weekday() - 4) % 7)
    dates = pd.date_range(end=end, periods=WEEKS, freq="W-FRI", tz="UTC")

    frames: list[pd.DataFrame] = []
    for name, ticker, start_px, vol in UNIVERSE:
        # Per-ticker drift so cross-section isn't degenerate. Roughly
        # split into "winners" (gold, axjo) and "losers" (lithium, uranium recently).
        drift = rng.uniform(-0.10, 0.12)
        closes = synthetic_walk(start_px, vol, drift, WEEKS, rng)
        frames.append(pd.DataFrame({
            "date": dates,
            "ticker": ticker,
            "close": closes,
        }))

    combined = pd.concat(frames, ignore_index=True).sort_values(["ticker", "date"])

    out_path = RAW_DIR / "prices.parquet"
    combined.to_parquet(out_path, index=False)
    log.info("Wrote %d rows for %d tickers (SYNTHETIC) → %s",
             len(combined), combined["ticker"].nunique(), out_path)

    # Marker so anyone inspecting the parquet knows it's fake
    (RAW_DIR / "_SYNTHETIC.txt").write_text(
        "prices.parquet was generated by scripts/_dev_seed.py. "
        "Replace by running scripts/ingest_prices.py against live yfinance.\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
